version: "3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      MYSQL_HOST: "127.0.0.1"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "felix"
      MYSQL_DATABASE: "challengedb"
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: felix
      MYSQL_DATABASE: challengedb
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

